export const actionLabelMap: Record<string, string> = {
  created: "tracking.action.created",
  status_change: "tracking.action.statusChange",
  sold: "tracking.action.sold",
  paid: "tracking.action.paid",
  cancelled: "tracking.action.cancelled",
  cancelled_sent: "tracking.action.cancelledSent",
  canceled_post_created: "tracking.action.cancelledPostCreated",
  cancelled_post_created: "tracking.action.cancelledPostCreated",
  canceled_post_received: "tracking.action.cancelledPostReceived",
  cancelled_post_received: "tracking.action.cancelledPostReceived",
  closed: "tracking.action.closed",
  received: "tracking.action.received",
  rollback: "tracking.action.rollback",
  sent: "tracking.action.sent",
  waiting: "tracking.action.waiting",
};
