export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "auth/login",
    MY_PROFILE: "auth/my-profile",
  },
  USERS: {
    BASE: "users",
    BY_ID: (id: string | number) => `users/${id}`,
    STATUS: (id: string | number) => `users/${id}/status`,
  },
  ADMINS: {
    BASE: "admins",
  },
  MARKETS: {
    BASE: "markets",
    BY_ID: (id: string | number) => `markets/${id}`,
  },
  COURIERS: {
    BASE: "couriers",
    BY_REGION: (regionId: string | number) => `couriers/region/${regionId}`,
  },
  REGIONS: {
    BASE: "region",
    BY_ID: (regionId: string | number) => `region/${regionId}`,
  },
  ORDERS: {
    BASE: "orders",
    BY_ID: (id: string | number) => `orders/${id}`,
    RECEIVE: "orders/receive",
    MARKETS_NEW: "orders/markets/new",
    MARKET_NEW: (marketId: string | number) => `orders/markets/${marketId}/new`,
    COURIER_ORDERS: "orders/courier/orders",
    FULL: (id: string | number) => `orders/${id}/full`,
    SELL: (id: string | number) => `orders/sell/${id}`,
    PARTLY_SELL: (id: string | number) => `orders/partly-sell/${id}`,
    ROLLBACK: (id: string | number) => `orders/rollback/${id}`,
    CANCEL: (id: string | number) => `orders/cancel/${id}`,
    EXTERNAL: "orders/external",
    EXTERNAL_ORDERS: "orders/external-orders",
    EXTERNAL_ORDERS_ALT: "orders/external_orders",
  },
  POSTS: {
    BASE: "post",
    NEW: "post/new",
    ON_THE_ROAD: "post/on-the-road",
    COURIER_OLD: "post/courier/old-posts",
    ORDERS_BY_POST_ID: (postId: string | number) => `post/orders/${postId}`,
    REJECTED_ORDERS_BY_POST_ID: (postId: string | number) => `post/orders/rejected/${postId}`,
    REJECTED: "post/rejected",
    COURIER_REJECTED: "post/courier/rejected",
    CANCEL: "post/cancel",
    BY_ID: (postId: string | number) => `post/${postId}`,
    RECEIVE: (postId: string | number) => `post/receive/${postId}`,
    CANCEL_RECEIVE: (postId: string | number) => `post/cancel/receive/${postId}`,
  },
  CASHBOX: {
    PAYMENT_COURIER: "cashbox/payment/courier",
    PAYMENT_MARKET: "cashbox/payment/market",
    USER_BY_ID: (id: string | number) => `cashbox/user/${id}`,
    MY_CASHBOX: "cashbox/my-cashbox",
    MAIN: "cashbox/main",
    SPEND: "cashbox/spend",
    FILL: "cashbox/fill",
    SHIFT_CURRENT: "cashbox/shift/current",
    SHIFT_OPEN: "cashbox/shift/open",
    SHIFT_CLOSE: "cashbox/shift/close",
    SHIFT_HISTORY: "cashbox/shift/history",
  },
  CASHBOX_HISTORY: {
    BY_ID: (id: string | number) => `cashbox-history/${id}`,
  },
  FINANCE: {
    CASHBOX_ALL_INFO: "finance/cashbox/all-info",
    CASHBOX_MAIN: "finance/cashbox/main",
    HISTORY: "finance/history",
    HISTORY_BY_ID: (id: string | number) => `finance/history/${id}`,
    OPERATION_TYPE: "finance/operation-type",
    SOURCE_TYPE: "finance/source-type",
    CASHBOX_TYPE: "finance/cashbox-type",
    CASHBOX_FINANCIAL_BALANCE: "finance/cashbox/financial-balanse",
  },
  ANALYTICS: {
    DASHBOARD: "analytics/dashboard",
    REVENUE: "analytics/revenue",
  },
  PRODUCTS: {
    BASE: "product",
    MY_PRODUCTS: "product/my-products",
    BY_ID: (id: string | number) => `product/${id}`,
    BY_MARKET_ID: (id: string | number) => `product/market/${id}`,
  },
  INTEGRATIONS: {
    BASE: "integrations",
    EXTERNAL_ORDERS: "integrations/external-orders",
    BY_ID: (id: string | number) => `integrations/${id}`,
  },
  NOTIFICATIONS: {
    BASE: "notifications",
    BY_ID: (id: string | number) => `notifications/${id}`,
  },
  BRANCHES: {
    BASE: "branches",
    BY_ID: (id: string | number) => `branches/${id}`,
    USERS: (id: string | number) => `branches/${id}/users`,
    EMPLOYEES: (id: string | number) => `branches/${id}/employees`,
    USER_BY_ID: (branchId: string | number, userId: string | number) =>
      `branches/${branchId}/users/${userId}`,
    SETTINGS: (id: string | number) => `branches/${id}/settings`,
    SETTING_BY_ID: (branchId: string | number, settingId: string | number) =>
      `branches/${branchId}/settings/${settingId}`,
  },
  IDENTITY: {
    USERS: "identity/users",
  },
} as const;
